### ISSUE TITLE
Error reading slide label because pixel data length is off by one

### ISSUE THREAD

**Issue by jleuschn** [imi-bigpicture/wsidicom#174]
When trying to read the label image of [this test slide](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/CMU-1-JP2K-33005.zip), a `WsiDicomFileError` is raised because the expected length of Pixel data is off by one:

Minimal example:
```
import os
from wsidicom import WsiDicom

# Prerequisite: download and extract the CMU-1-JP2K-33005 test image at `PATH`:
# https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/CMU-1-JP2K-33005.zip
PATH = "CMU-1-JP2K-33005"

slide = WsiDicom.open(PATH)
label_image = slide.read_label()  # Fails
print("wsidicom loaded label image of size", label_image.size)

# -------- for reference: open the image with openslide --------

from openslide import OpenSlide

slide_openslide = OpenSlide(
    next(os.path.join(PATH, f) for f in os.listdir(PATH) if f.endswith(".dcm"))
)
label_image_openslide = slide_openslide.associated_images["label"]
print("openslide loaded label image of size", label_image_openslide.size)
```
causes this exception:
```
Traceback (most recent call last):
  [...]
  File "[...]/wsidicom/wsidicom.py", line 485, in read_label
    return label.get_default_full()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/group/group.py", line 253, in get_default_full
    image = self.get_region(region, z, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/group/group.py", line 289, in get_region
    image = instance.image_data.stitch_tiles(region, path, z, threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/instance/image_data.py", line 474, in stitch_tiles
    tile = self._get_decoded_tile(tile_region.start, z, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/instance/wsidicom_image_data.py", line 167, in _get_decoded_tile
    frame = self._get_tile_frame(frame_index)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/wsidicom_file_image_data.py", line 123, in _get_tile_frame
    tile_frame = reader.read_frame(frame_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/wsidicom_reader.py", line 150, in read_frame
    frame_position, frame_length = self.frame_positions[frame_index]
                                   ^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/wsidicom_reader.py", line 124, in frame_positions
    return self.frame_index.index
           ^^^^^^^^^^^^^^^^
  File "[...]/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/wsidicom_reader.py", line 95, in frame_index
    return self._get_frame_index()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/wsidicom_reader.py", line 159, in _get_frame_index
    return NativePixelData(
           ^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/frame_index/native_pixel_data_frame.py", line 38, in __init__
    super().__init__(file, pixel_data_start, frame_count)
  File "[...]/wsidicom/file/io/frame_index/frame_index.py", line 33, in __init__
    self._pixels_start = self._get_pixels_start()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/wsidicom/file/io/frame_index/native_pixel_data_frame.py", line 45, in _get_pixels_start
    self._validate_pixel_data_start()
  File "[...]/wsidicom/file/io/frame_index/native_pixel_data_frame.py", line 78, in _validate_pixel_data_start
    super()._validate_pixel_data_start(expected_length)
  File "[...]/wsidicom/file/io/frame_index/frame_index.py", line 95, in _validate_pixel_data_start
    raise WsiDicomFileError(
wsidicom.errors.WsiDicomFileError: <wsidicom.file.io.wsidicom_io.WsiDicomIO object at [...]>: Expected 537543 length when reading Pixel data, got 537544.
```

I don't know whether the file is actually corrupt or should be readable by wsidicom, but wanted to report it since openslide is able to read the label image.

**Comment by erikogabrielsson** [comment]
Thanks for reporting this issue @jleuschn.

The file is not corrupt. The pixel data should actually always have an even length (see entry for `OB` [here](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html)).

[This commit](https://github.com/imi-bigpicture/wsidicom/commit/6f9ab078185c360b4e1e2ed14bc56ccb3874a918) fixes this, hope to release it soon.

**Comment by jleuschn** [comment]
Nice, thanks for the quick fix!
